import type { Metadata } from "next";
import localFont from "next/font/local";
import { AppProvider } from "@/context/context"; // Import the provider
import { Toaster } from "react-hot-toast";

import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import "./globals.css";

// Load your custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Set the page metadata
export const metadata: Metadata = {
  title: "365 Fitness",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} min-h-screen bg-zinc-100 text-zinc-800  ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <NavBar />
          <Toaster />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
